### ISSUE TITLE
Just won't generate same result with GA

### ISSUE THREAD

**Issue by HaskellZhangSong** [mstksg/otp-authenticator#1]

**Comment by HaskellZhangSong** [comment]
checked with GA on my phone and clojure one-time, the result is just not correct.

**Comment by mstksg** [comment]
Just commenting to acknowledge that I've noticed this too.  It has matched in the past with GA, but seems to have changed.  The libraries used might have changed behavior; will investigate.

**Comment by mstksg** [comment]
Should be fixed as of 720dd53ffb15ab1ba50002af82deb488f449372d
